### PR TITLE
Upgrade actix, gettext

### PR DESCRIPTION
**Pull request by asonix**
Bump actix to 1.0, and gettext to 0.4

### CODE REVIEW

**Comment by AnaGelez** [comment]
Does it make actix the default too?

**Comment by asonix** [comment]
Yeah it does. I figured it wouldnt be a huge issue if y'all are switching to actix, but it does make the name of the crate, rocket_i18n, a bit confusing

**Comment by AnaGelez** [comment]
I will see if I can rename it to something like web-i18n. Anyway, thanks for the PR!

**Comment by trinity-1686a** [comment]
if framework support is changed, version should probably be bumped to 0.5.0 to mark a breaking change

**Comment by elegaanz** [comment]
Renaming it should do the job too, right?

**Comment by trinity-1686a** [comment]
I have no idea of how crates io support renaming. Wouldn't it effectively create a totally different crate?

**Comment by elegaanz** [comment]
Probably, yes. But we can probably yank all the other versions of rocket-i18n after that, I and tell people to use web-i18n instead?

**Comment by igalic** [comment]
i'd publish a new crate, and deprecate the old…
(if there was such a process)

*******

Before renaming / republishing it as `web-i18n`, we should maybe hit up the [warp](https://github.com/seanmonstar/warp) folks that we have a thing that's cool and they want to use add support for their framework too

**Comment by elegaanz** [comment]
And tide too… and gotham… and…

(more seriously, feel free to do so, but I won't add support for warp myself)

**Pull request merged**
